#baseURL = 'https://awakeninig-retreat.netlify.app'
#baseURL = 'https://woa.cicy.de'
baseURL = "https://worldofawakening.netlify.app/"
languageCode = 'en-us'
paginate = 6
#theme= "coHub"
title = 'Retreat - World of Awakening'

[Menu]
  # Main Menu

  [[menu.Main]]
  name = "Retreat"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2


[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://worldofawakening.com/\" target=\"_blank\">World of Awakening - Retreats </a>"
  fabFormURL =  "https://fabform.io/url-"
  googleAnalytics = "G-xxxxxxxx"
  logo = "images/corporate/world-of-awakening-logo.png"
  footerlogo = "images/corporate/world-of-awakening-logo.png"
  footerDescription = "woa is a nonprofit organisation operating worldwide"

  [params.address]
  address = "US and AMERICA "
  email = "hello@worldofawakening.com"
  openingDesc = "Give us a message or request a conversation."
  openingHours = "Eastern Standard Time(EST; UTC-4:00)"
  telegram = "@nicarera"
  whatsApp = "+18 657 650 668"
  phone = "+18657650668"

  [params.addressEU]
  address = "EUROPE"
  email = "hello@worldofawakening.com"
  openingDesc = "Give us a message or request a conversation."
  openingHours = "Eastern European Time (EET; UTC+02:00)"
  telegram = "@Kjenta_cooren"
  whatsApp = "+32492522240"
  phone = "+32492522240"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/AWKNtheWorld/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/world_of_awakening/"
  weight = 3


